### ISSUE TITLE
File won't get parsed

### ISSUE THREAD

**Issue by burtek** [rahra/parsefsh#2]
I get empty gpx/csv files when parsing my [ARCHIVE.FSH file](https://app.box.com/s/497875sjnjxl6qsgeaufjv8ka9hue0hz). Any idea why?

**Comment by rahra** [comment]
I justed tested your file and it worked for me. Did you run parsefsh correctly?

parsefsh -f gpx < ARCHIVE.FSH > ARCHIVE.GPX

**Comment by burtek** [comment]
Yes, I did. I'm using qt-mingw on Win7x64 to build the tool - may that be the cause?

**Comment by burtek** [comment]
I guess. I got it working on linux. Sorry for that.
