### ISSUE TITLE
Linker error on Ubuntu 18.04

### ISSUE THREAD

**Issue by michal2229** [rahra/parsefsh#4]
I have a problem as described [here](https://www.oipapio.com/question-11315421).
When trying to make the binaries, I have errors about missing math functions, like:
```
undefined reference to `pow'
```
and so on. 

Solution described in linked topic:
```
The simplest solution is simply to change [in Makefile]:
LDFLAGS = -lm
to
LDLIBS = -lm
```
enabled me to compile and use the binary.

Another fix was to compile it using g++ and add *-fpermissive* flag.

**Comment by rahra** [comment]
Oh, I see, you are right.
Thanks, I'll fix it.

**Comment by rahra** [comment]
Fixed in https://github.com/rahra/parsefsh/commit/8fb47a6fc71553ea62a8ba95016cd2a6aeb2d649.
